# Databricks notebook source
# MAGIC %sql
# MAGIC SELECT		DISTINCT L.CONTRACT,L.CURRENCY,L.PERIOD,COALESCE(L.TRAN_TYPE,'') TRAN_TYPE,COALESCE(L.PM_TYPE,'') PM_TYPE,COALESCE(L.EVENT,'')  EVENT,COALESCE(L.SUB_EVENT,'')  SUB_EVENT
# MAGIC             ,A.CONTRACT A_CONTRACT,A.CURRENCY A_CURRENCY,A.PERIOD A_PERIOD,COALESCE(A.TRAN_TYPE,'') A_TRAN_TYPE,COALESCE(A.PM_TYPE,'') A_PM_TYPE,COALESCE(A.EVENT,'')  A_EVENT,COALESCE(A.SUB_EVENT,'')  A_SUB_EVENT
# MAGIC FROM		mymi_pre_gxlp.DBO_LEDGER L 
# MAGIC INNER JOIN	mymi_pre_gxlp.DBO_ACCRUAL A	
# MAGIC ON			COALESCE(L.CONTRACT,'') = COALESCE(A.CONTRACT,'')
# MAGIC AND			COALESCE(L.CURRENCY,'') = COALESCE(A.CURRENCY,'')
# MAGIC AND			COALESCE(L.TRAN_TYPE,'') = COALESCE(A.TRAN_TYPE,'')
# MAGIC AND			COALESCE(L.PM_TYPE,'') = COALESCE(A.PM_TYPE,'')
# MAGIC AND			COALESCE(L.EVENT,'')  = COALESCE(A.EVENT,'') 
# MAGIC AND			COALESCE(L.SUB_EVENT,'') = COALESCE(A.SUB_EVENT,'')
# MAGIC WHERE		A.PERIOD	< L.PERIOD 
# MAGIC AND    L.CONTRACT = 'ZP600J09R001'

# COMMAND ----------

# DBTITLE 1,Examples for Allocation
# MAGIC %sql
# MAGIC /*
# MAGIC 		period	contract	event	sub_event	TRAN_TYPE	PM_TYPE	currency
# MAGIC 		202007	ZP160A16S001	160521	160521	ACL	 	USD
# MAGIC 
# MAGIC 		period	contract	event	sub_event	TRAN_TYPE	PM_TYPE	currency
# MAGIC 		201704	ZR200Q16A001	NULL	NULL	CSH	NULL	EUR
# MAGIC 
# MAGIC 		period	contract	event	sub_event	TRAN_TYPE	PM_TYPE	currency
# MAGIC 		202101	ZP201E07A001	SMALL	SMALL	ACL	 	GBP
# MAGIC */

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW Vw_Agg_Ledger 
# MAGIC AS
# MAGIC SELECT  CONTRACT
# MAGIC ,VERSION_NO
# MAGIC ,BROKER_CD
# MAGIC ,BROKER_RF
# MAGIC ,ORI_REF
# MAGIC ,REIN_CD
# MAGIC ,EVENT
# MAGIC ,SUB_EVENT
# MAGIC ,EVENT_DESC
# MAGIC ,ACCOUNT_ID
# MAGIC ,ACCOUNT_DESC
# MAGIC ,TRAN_TYPE
# MAGIC ,TRANS_DATE
# MAGIC ,EFFTV_DATE
# MAGIC ,SETT_KEY
# MAGIC ,LETTER_NO
# MAGIC ,SETT_DATE
# MAGIC ,AGREED
# MAGIC ,CURRENCY
# MAGIC ,CCY_ORG
# MAGIC ,SUM(AMT_CURR) AMT_CURR
# MAGIC ,SUM(AMT_ORIG) AMT_ORIG
# MAGIC ,NARR
# MAGIC ,SETT_IND
# MAGIC ,SOURCE
# MAGIC ,AGENCY_CD
# MAGIC ,LPSO_NO
# MAGIC ,LPSO_VER
# MAGIC ,LPSO_DATE
# MAGIC ,PERIOD
# MAGIC ,DW_EXPORT
# MAGIC ,ALLOC_DATE
# MAGIC ,LORS_RISK_CODE
# MAGIC ,SETT_PERIOD
# MAGIC ,AGREED_PERIOD
# MAGIC ,MSG_REFNO
# MAGIC ,PAY_DATE
# MAGIC ,BROKER_RF2
# MAGIC ,LOCKED_FLAG
# MAGIC ,CO_REIN
# MAGIC ,PM_TYPE
# MAGIC ,ENTITY_CD
# MAGIC ,LORS_YOA
# MAGIC ,SETT_DUE_DATE
# MAGIC ,ENTRY_TYPE
# MAGIC FROM mymi_pre_gxlp.DBO_LEDGER 
# MAGIC GROUP BY  CONTRACT
# MAGIC ,VERSION_NO
# MAGIC ,BROKER_CD
# MAGIC ,BROKER_RF
# MAGIC ,ORI_REF
# MAGIC ,REIN_CD
# MAGIC ,EVENT
# MAGIC ,SUB_EVENT
# MAGIC ,EVENT_DESC
# MAGIC ,ACCOUNT_ID
# MAGIC ,ACCOUNT_DESC
# MAGIC ,TRAN_TYPE
# MAGIC ,TRANS_DATE
# MAGIC ,EFFTV_DATE
# MAGIC ,SETT_KEY
# MAGIC ,LETTER_NO
# MAGIC ,SETT_DATE
# MAGIC ,AGREED
# MAGIC ,CURRENCY
# MAGIC ,CCY_ORG
# MAGIC ,NARR
# MAGIC ,SETT_IND
# MAGIC ,SOURCE
# MAGIC ,AGENCY_CD
# MAGIC ,LPSO_NO
# MAGIC ,LPSO_VER
# MAGIC ,LPSO_DATE
# MAGIC ,PERIOD
# MAGIC ,DW_EXPORT
# MAGIC ,ALLOC_DATE
# MAGIC ,LORS_RISK_CODE
# MAGIC ,SETT_PERIOD
# MAGIC ,AGREED_PERIOD
# MAGIC ,MSG_REFNO
# MAGIC ,PAY_DATE
# MAGIC ,BROKER_RF2
# MAGIC ,LOCKED_FLAG
# MAGIC ,CO_REIN
# MAGIC ,PM_TYPE
# MAGIC ,ENTITY_CD
# MAGIC ,LORS_YOA
# MAGIC ,SETT_DUE_DATE
# MAGIC ,ENTRY_TYPE

# COMMAND ----------

# MAGIC %sql
# MAGIC 
# MAGIC -- Use consistent logic to get last closed period with other GXLP notebooks
# MAGIC 
# MAGIC CREATE OR REPLACE VIEW VW_AggAccrual
# MAGIC AS
# MAGIC SELECT 
# MAGIC A.CONTRACT A_CONTRACT,
# MAGIC A.CURRENCY A_CURRENCY,
# MAGIC A.PERIOD A_PERIOD,
# MAGIC COALESCE(A.TRAN_TYPE,'') A_TRAN_TYPE,
# MAGIC COALESCE(A.PM_TYPE,'') A_PM_TYPE,
# MAGIC COALESCE(A.EVENT,'')  A_EVENT,
# MAGIC COALESCE(A.SUB_EVENT,'')  A_SUB_EVENT,
# MAGIC AC_STAT1,
# MAGIC AC_STAT10,
# MAGIC AC_STAT2,
# MAGIC AC_STAT3,
# MAGIC AC_STAT4,
# MAGIC AC_STAT5,
# MAGIC AC_STAT6,
# MAGIC AC_STAT7,
# MAGIC AC_STAT8,
# MAGIC AC_STAT9,
# MAGIC AC_YEAR,
# MAGIC entity_Cd,
# MAGIC SUM(AMT_NET) AS AMT_NET_NR
# MAGIC FROM mymi_pre_gxlp.DBO_ACCRUAL A
# MAGIC WHERE PERIOD = (SELECT PrevGXLPPeriod  FROM   MyMI_Abst_GXLP.Stg10_ORIGXLPPeriodForMyMI WHERE IsMDMCurrentPeriod = True)
# MAGIC group by A.CONTRACT,A.CURRENCY ,A.PERIOD ,COALESCE(A.TRAN_TYPE,'') ,COALESCE(A.PM_TYPE,'') ,COALESCE(A.EVENT,'')  ,COALESCE(A.SUB_EVENT,'')  ,AC_STAT1,
# MAGIC AC_STAT10,
# MAGIC AC_STAT2,
# MAGIC AC_STAT3,
# MAGIC AC_STAT4,
# MAGIC AC_STAT5,
# MAGIC AC_STAT6,
# MAGIC AC_STAT7,
# MAGIC AC_STAT8,
# MAGIC AC_STAT9,
# MAGIC AC_YEAR,Entity_CD

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Need another group by on CMD 3 output with agrregated values excluding AC codes and use cmd 3 and cmd 4 to generate percentages
# MAGIC CREATE OR REPLACE VIEW VW_AggAccrual_Without_ACStats
# MAGIC AS
# MAGIC SELECT Contract,Currency,Period,Tran_Type,PM_Type,Event,SUB_EVENT,Entity_CD,sum(AMT_NET) as AMT_NET_DR
# MAGIC FROM mymi_pre_gxlp.DBO_ACCRUAL A  WHERE PERIOD = (SELECT PrevGXLPPeriod  FROM   MyMI_Abst_GXLP.Stg10_ORIGXLPPeriodForMyMI WHERE IsMDMCurrentPeriod = True)
# MAGIC group by Contract,Currency,Period,Tran_Type,PM_Type,Event,SUB_EVENT,Entity_CD

# COMMAND ----------

# MAGIC %sql
# MAGIC 
# MAGIC SELECT 
# MAGIC         L.*,
# MAGIC         AC_STAT1,
# MAGIC         AC_STAT10,
# MAGIC         AC_STAT2,
# MAGIC         AC_STAT3,
# MAGIC         AC_STAT4,
# MAGIC         AC_STAT5,
# MAGIC         AC_STAT6,
# MAGIC         AC_STAT7,
# MAGIC         AC_STAT8,
# MAGIC         AC_STAT9,
# MAGIC         AC_YEAR,
# MAGIC         AMT_CURR*COALESCE((AMT_NET_NR/AMT_NET_DR),1) Allocated_AMT_CURR
# MAGIC FROM    Vw_Agg_Ledger L
# MAGIC LEFT JOIN vw_aggaccrual_without_acstats  A
# MAGIC ON    COALESCE(L.CONTRACT,'') = COALESCE(A.CONTRACT,'')
# MAGIC AND   COALESCE(L.CURRENCY,'') = COALESCE(A.CURRENCY,'')
# MAGIC AND   COALESCE(L.TRAN_TYPE,'') = COALESCE(A.Tran_Type,'')
# MAGIC AND   COALESCE(L.PM_TYPE,'') = COALESCE(A.PM_TYPE,'')
# MAGIC AND   COALESCE(L.EVENT,'') = COALESCE(A.EVENT,'')
# MAGIC AND   COALESCE(L.SUB_EVENT,'') = COALESCE(A.SUB_EVENT,'')
# MAGIC AND   COALESCE(L.ENTITY_CD,'') = COALESCE(A.ENTITY_CD,'')
# MAGIC JOIN  vw_aggaccrual AAC
# MAGIC ON      AAC.A_CONTRACT = A.Contract
# MAGIC       AND AAC.A_CURRENCY = A.CURRENCY
# MAGIC       AND AAC.A_TRAN_TYPE = A.Tran_Type
# MAGIC       AND AAC.A_PM_Type = A.PM_Type
# MAGIC       AND AAC.A_EVENT = A.Event
# MAGIC       AND AAC.A_SUB_EVENT = A.SUB_EVENT
# MAGIC       AND AAC.Entity_CD = A.Entity_CD
# MAGIC   --WHERE  L.CONTRACT = 'ZP600J09R001'
# MAGIC   WHERE A_CONTRACT = 'ZM501Z16R002' AND A_CURRENCY= 'USD' AND A_TRAN_TYPE ='PM' AND A_PM_TYPE = 'S' AND A_EVENT = '' AND A_SUB_EVENT = '' AND AAC.ENTITY_CD = 2987

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT COUNT(*),PERIOD
# MAGIC FROM Vw_Agg_Ledger
# MAGIC GROUP BY PERIOD
# MAGIC ORDER BY PERIOD
# MAGIC  --WHERE   CONTRACT = 'ZP600J09R001'  AND CURRENCY = 'EUR' AND TRAN_TYPE = 'PM' AND PM_TYPE = 'S' AND EVENT = '' AND Entity_CD = 2987 AND SUB_EVENT =  ''

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT *
# MAGIC FROM mymi_pre_gxlp.DBO_ACCRUAL
# MAGIC WHERE  CONTRACT = 'ZP600J09R001'  AND CURRENCY = 'EUR' AND TRAN_TYPE = 'PM' AND PM_TYPE = 'S' AND EVENT = '' AND Entity_CD = 2987 AND SUB_EVENT =  '' AND PERIOD = 202204 --AND (AMT_NET BETWEEN -7600 AND -7550)
# MAGIC ORDER BY AMT_NET
# MAGIC --Contract,Currency,Period,Tran_Type,PM_Type,Event,SUB_EVENT,Entity_CD

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT A_Contract,A_Currency,A_Tran_Type,A_PM_Type,A_Event,A_SUB_EVENT,Entity_CD,COUNT(AMT_NET_DR) FROM (
# MAGIC SELECT AAC.*,AMT_NET_DR,(AMT_NET_NR/AMT_NET_DR)
# MAGIC FROM vw_aggaccrual_without_acstats  A
# MAGIC JOIN  vw_aggaccrual AAC
# MAGIC ON      AAC.A_CONTRACT = A.Contract
# MAGIC       AND AAC.A_CURRENCY = A.CURRENCY
# MAGIC       AND AAC.A_TRAN_TYPE = A.Tran_Type
# MAGIC       AND AAC.A_PM_Type = A.PM_Type
# MAGIC       AND AAC.A_EVENT = A.Event
# MAGIC       AND AAC.A_SUB_EVENT = A.SUB_EVENT
# MAGIC       AND AAC.Entity_CD = A.Entity_CD
# MAGIC      )A
# MAGIC      GROUP BY A_Contract,A_Currency,A_Tran_Type,A_PM_Type,A_Event,A_SUB_EVENT,Entity_CD

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT AAC.*,AMT_NET_DR,(AMT_NET_NR/AMT_NET_DR)
# MAGIC FROM vw_aggaccrual_without_acstats  A
# MAGIC JOIN  vw_aggaccrual AAC
# MAGIC ON      AAC.A_CONTRACT = A.Contract
# MAGIC       AND AAC.A_CURRENCY = A.CURRENCY
# MAGIC       AND AAC.A_TRAN_TYPE = A.Tran_Type
# MAGIC       AND AAC.A_PM_Type = A.PM_Type
# MAGIC       AND AAC.A_EVENT = A.Event
# MAGIC       AND AAC.A_SUB_EVENT = A.SUB_EVENT
# MAGIC       AND AAC.Entity_CD = A.Entity_CD
# MAGIC       WHERE A_CONTRACT = 'ZM501Z16R002' AND A_CURRENCY= 'USD' AND A_TRAN_TYPE ='PM' AND A_PM_TYPE = 'S' AND A_EVENT = '' AND A_SUB_EVENT = '' AND AAC.ENTITY_CD = 2987

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT *
# MAGIC from mymi_pre_gxlp.dbo_ledger
# MAGIC  WHERE CONTRACT = 'ZM501Z16R002' AND CURRENCY= 'USD' AND TRAN_TYPE ='PM' AND PM_TYPE = 'S' AND EVENT = '' AND SUB_EVENT = '' AND ENTITY_CD = 2987
